void MCMCDyn_wrapper (double *heads, double *tails, double *dnedges,
		   double *dn, int *dflag, double *bipartite, 
		   int *nterms, char **funnames,
		   char **sonames, 
		   char **MHproposaltype, char **MHproposalpackage,
		   double *inputs, 
		   double *theta0, double *samplesize, double *sample,
		   double *burnin, double *interval,
		   int *newnetwork, 
		   int *fVerbose, 
		   double *proportionbreak,
		   int *attribs, int *maxout, int *maxin, int *minout,
		   int *minin, int *condAllDegExact, int *attriblength, 
		   double *maxedges,
		   double *mheads, double *mtails, double *mdnedges,
		   int *mdflag);
void MCMCSampleDyn (char *MHproposaltype, char *MHproposalpackage,
		 double *theta, double *networkstatistics, 
		 long int samplesize, long int burnin, 
		 long int interval, int hammingterm, int fVerbose,
	       	 double proportionbreak, Network *nwp, Model *m, DegreeBound *bd);
void MetropolisHastingsDyn (MHproposal *MHp,
			 double *theta, double *statistics, 
			 long int nsteps, long int *staken,
			 int hammingterm, int fVerbose,
			 double *proportionbreak,
			 Network *nwp, Model *m, DegreeBound *bd);
