control.stergm<-function(prop.weights.form="default",prop.args.form=NULL,
                         prop.weights.diss="default",prop.args.diss=NULL,
                         compress=FALSE,
                         SAN.burnin=10000,
                         SAN.interval=1000,
                         maxNumDyadTypes=1e+6, 
                         maxedges=20000,
                         maxchanges=1000000,
                         maxMPLEsamplesize=100000,
                         MPLEtype=c("glm", "penalized"),
                         trace=0,
                         sequential=TRUE,
                         drop=TRUE,
                         style=c("Robbins-Monro","SPSA", "SPSA2", "Nelder-Mead"),
                         RM.phase1n_base=7,
                         RM.phase2n_base=100,
                         RM.phase2sub=4,
                         RM.init_gain=0.5,
                         RM.phase3n=500,
                         RM.interval=100,
                         RM.burnin=1000,
                         PILA.gamma=.99,
                         PILA.steplength=.1,
                         SPSA.a=1,
                         SPSA.alpha=0.602,
                         SPSA.A=100,
                         SPSA.c=1,
                         SPSA.gamma=0.101,
                         SPSA.iterations=1000,
                         SPSA.interval=1000,
                         SPSA.burnin=1000,
                         NM.abstol=0,
                         NM.reltol=sqrt(.Machine$double.eps),
                         NM.alpha=1,
                         NM.beta=.5,
                         NM.gamma=2,
                         NM.maxit=500,
                         NM.interval=1000,
                         NM.burnin=1000,
                         packagenames="ergm",
                         parallel=0){
  control<-list()
  for(arg in names(formals(sys.function())))
    control[[arg]]<-get(arg)
  
  control$MPLEtype<-match.arg(MPLEtype)
  control$style<-match.arg(style)
  control
}
