# This stuff used to be in ergm.mcmcslave.R.  Don't know if we need it.

#mcmcdynslave <- function(Clist,MHproposal,eta0,MCMCparams,maxedges,verbose) {
#   'library(mpi)',
#   'library(rsprng)',
#   'library(MASS)',
#   'PARTAG <- 1; RESTAG <- 2; EXITTAG <- 3',
#   'SLAVEDIR <- paste(getwd(),"/",mpibasename,".run",sep="")',
#   'load(file=paste(SLAVEDIR,"/",mpibasename,".common.RData",sep=""))',
#   'mytid <- .PVM.mytid ()',
#   'parentid <- .PVM.parent ()',
#   'repeat {',
#   '# wait for a message from the parent with any tag',
#   'bid <- .PVM.recv (tid = parentid, msgtag = -1)',
#   '# get info about the message',
#   'info<-.PVM.bufinfo (bid)',
#   'if (info[["msgtag"]] == EXITTAG) break  # exit the process',
#   '#',
#   '# Input parameters',
#   '#',
#   'iparam <- .PVM.upkintvec()',
#   '# establish RNG state',
#   'r <- iparam[1]; it<-iparam[2]',
#   'oldrng<-init.sprng(nstream=r,streamno=it-1,seed=1)',
#   'cat("Iteration",it,"of",r,"\\n")',
##  paste('library(',packagename,')',sep=""),
#   paste('library(','ergm',')',sep=""),
#'z <- .C("MCMCDyn_wrapper",',
#'as.integer(Clist.form$heads), as.integer(Clist.form$tails),',
#'as.integer(Clist.form$nedges), as.integer(Clist.form$maxpossibleedges), as.integer(Clist.form$n),',
#'as.integer(Clist.form$dir), as.integer(Clist.form$bipartite),',
#'as.integer(Clist.diss$order.code),',
#'as.integer(Clist.form$nterms),',
#'as.character(Clist.form$fnamestring),',
#'as.character(Clist.form$snamestring),',
#'as.character(MHproposal.form$name), as.character(MHproposal.form$package),',
#'as.double(Clist.form$inputs), as.double(theta0),',
#'as.integer(Clist.diss$nterms),',
#'as.character(Clist.diss$fnamestring),',
#'as.character(Clist.diss$snamestring),',
#'as.character(MHproposal.diss$name), as.character(MHproposal.diss$package),',
#'as.double(Clist.diss$inputs), as.double(gamma0),',
#'as.integer(MHproposal$bd$attribs),',
#'as.integer(MHproposal$bd$maxout), as.integer(MHproposal$bd$maxin),',
#'as.integer(MHproposal$bd$minout), as.integer(MHproposal$bd$minin),',
#'as.integer(MHproposal$bd$condAllDegExact), as.integer(length(MHproposal$bd$attribs)),',
#'as.double(MCMCparams$nsteps), as.integer(MCMCparams$dyninterval),',
#'as.double(MCMCparams$burnin), as.double(MCMCparams$interval),',
#'s.form = as.double(cbind(t(MCMCparams$stats.form),matrix(0,nrow=length(model.form$coef.names),ncol=MCMCparams$nsteps))),',
#'s.diss = as.double(cbind(t(MCMCparams$stats.diss),matrix(0,nrow=length(model.diss$coef.names),ncol=MCMCparams$nsteps))),',
#'newnwheads = integer(maxchanges), newnwtails = integer(maxchanges),',
#'as.double(maxchanges),',
#'diffnwtime = integer(maxchanges),',
#'diffnwheads = integer(maxchanges),',
#'diffnwtails = integer(maxchanges),',
#'as.integer(verbose),',
#'PACKAGE="ergm")',
#   '# save the results',
#   'z <- list(s.form=z$s.form,s.dissolve=z$s.dissolve,newnwhead=z$newnwhead,newnwtail=z$newnwtail,diffnwhead=z$diffnwhead,',
#   '       diffnwtail=z$diffnwtail,diffnwtime=z$diffnwtime)',
#   'save(z,',
#   '  file=paste(SLAVEDIR,"/",mpibasename,".out.",it,".RData",sep=""))',

# snow


