# the MHproposal look-up table: these are the combinations of constraints, weights,
# and proposals that are supported

MHproposals<-
  #         Class Constraints     Reference              Weights        MHP
  rbind(I(c("c", "",              "Bernoulli",  "default",      "TNT")),
          c("c", "",              "Bernoulli",  "TNT",          "TNT"),
          c("c", "",              "Bernoulli",  "random",       "randomtoggle"),
          c("c", "",              "Bernoulli",  "TNT10",        "TNT10"),
          c("c", "bd",            "Bernoulli",  "default",       "TNT"),
          c("c", "bd",            "Bernoulli",  "TNT",           "TNT"),
          c("c", "bd",            "Bernoulli",  "random",       "randomtoggle"),
          c("c", "bd+edges",      "Bernoulli",  "default",      "ConstantEdges"),
          c("c", "bd+edges",      "Bernoulli",      "random",       "ConstantEdges"),          
          c("c", "degrees",       "Bernoulli",       "default",      "CondDegree"),
          c("c", "degrees",       "Bernoulli",       "random",       "CondDegree"),
          c("c", "degreessimple", "Bernoulli",       "default",      "CondDegreeSimple"),
          c("c", "degreessimple", "Bernoulli",       "random",       "CondDegreeSimple"),
          c("c", "degreesTetrad", "Bernoulli",       "default",      "CondDegreeTetradToggles"),
          c("c", "degreesTetrad", "Bernoulli",       "random",       "CondDegreeTetradToggles"),
          c("c", "degreesHexad",  "Bernoulli",       "default",      "CondDegreeHexadToggles"),
          c("c", "degreesHexad",  "Bernoulli",       "random",       "CondDegreeHexadToggles"),

          c("c", "degreedist",    "Bernoulli",    "default",      "CondDegreeDist"),
          c("c", "degreedist",    "Bernoulli",    "random",       "CondDegreeDist"), 
          c("c", "indegreedist",  "Bernoulli",  "default",      "CondInDegreeDist"),
          c("c", "indegreedist",  "Bernoulli",  "random",       "CondInDegreeDist"), 
          c("c", "outdegreedist", "Bernoulli",  "default",      "CondOutDegreeDist"),
          c("c", "outdegreedist", "Bernoulli",  "random",       "CondOutDegreeDist"), 
#          c("c", "indegrees",    "Bernoulli",     "default",      "CondInDegree"),
#          c("c", "indegrees",    "Bernoulli",     "random",       "CondInDegree"),
#          c("c", "outdegrees",   "Bernoulli",    "default",      "CondOutDegree"),
#          c("c", "outdegrees",   "Bernoulli",    "random",       "CondOutDegree"),
          c("c", "edges",         "Bernoulli",         "default",      "ConstantEdges"),
          c("c", "edges",         "Bernoulli",         "random",       "ConstantEdges"),
          c("c", "hamming",       "Bernoulli",       "default",      "HammingTNT"),
          c("c", "hamming",       "Bernoulli",       "random",       "HammingTNT"),
          c("c", "edges+hamming", "Bernoulli", "default",      "HammingConstantEdges"),
          c("c", "edges+hamming", "Bernoulli", "random",       "HammingConstantEdges"),
          c("c", "observed",      "Bernoulli",      "default",      "randomtoggleNonObserved"),
          c("c", "observed",      "Bernoulli",      "random",       "randomtoggleNonObserved"),
          c("c", "bd+observed",   "Bernoulli",      "default",      "randomtoggleNonObserved"),
          c("c", "bd+observed",   "Bernoulli",      "random",       "randomtoggleNonObserved"),
          c("f", "",              "Bernoulli",              "default",      "formationTNT"),
          c("f", "",              "Bernoulli",              "TNT",          "formationTNT"),
          c("f", "",              "Bernoulli",              "random",       "formation"),
          c("f", "bd",            "Bernoulli",            "default",      "formationTNT"),
          c("f", "bd",            "Bernoulli",            "TNT",          "formationTNT"),
          c("f", "bd",            "Bernoulli",            "random",       "formation"),
          c("d", "",              "Bernoulli",              "default",      "dissolution"),
          c("d", "",              "Bernoulli",              "random",       "dissolution"),
          c("d", "bd",            "Bernoulli",            "default",      "dissolution"),
          c("d", "bd",            "Bernoulli",            "random",       "dissolution"),
          c("fmle", "",           "Bernoulli",            "default",      "formationMLE"),
          c("fmle", "",           "Bernoulli",            "random",       "formationMLE"),
          c("fmle", "observed",   "Bernoulli",            "default",      "formationNonObservedMLE"),
          c("fmle", "observed",   "Bernoulli",            "random",       "formationNonObservedMLE"),
          c("fmle", "bd",         "Bernoulli",            "default",      "formationMLE"),
          c("fmle", "bd",         "Bernoulli",            "random",       "formationMLE"),
          c("dmle", "",           "Bernoulli",            "default",      "dissolutionMLE"),
          c("dmle", "",           "Bernoulli",            "random",       "dissolutionMLE"),
          c("dmle", "observed",   "Bernoulli",            "default",      "dissolutionNonObservedMLE"),
          c("dmle", "observed",   "Bernoulli",            "random",       "dissolutionNonObservedMLE"),
          c("dmle", "bd",         "Bernoulli",            "default",      "dissolutionMLE"),
          c("dmle", "bd",         "Bernoulli",            "random",       "dissolutionMLE"),
          c("c", "",              "Poisson",  "default",      "Poisson"),
          c("c", "",              "Poisson",  "random",       "Poisson"),
          c("c", "observed",      "Poisson",  "default",      "PoissonNonObserved"),
          c("c", "observed",      "Poisson",  "random",       "PoissonNonObserved"),
          c("c", "",              "DescRank",  "default",      "DescRank"),
          c("c", "",              "DescRank",  "random",       "DescRank"),
          c("c", "",              "StdNormal",  "default",      "StdNormal"),
          c("c", "",              "StdNormal",  "random",       "StdNormal"),
          c("c", "ranks",         "StdNormal",  "default",      "StdNormalRank"),
          c("c", "ranks",         "StdNormal",  "random",       "StdNormalRank")

        )
MHproposals <- data.frame(I(MHproposals[,1]), I(MHproposals[,2]), 
                          I(MHproposals[,3]), I(MHproposals[,4]),
                          I(MHproposals[,5]))
colnames(MHproposals)<-c("Class","Constraints","Reference","Weights","MHP")
