# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on: [push, pull_request]

name: lint-changed-warnings.yaml

permissions: read-all

jobs:
  lint-changed-warnings:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::gh
          dependencies: FALSE
          working-directory: base

      - name: Prevent a redundant run
        if: github.event_name != 'pull_request'
        run: |
          prs <- gh::gh("GET /repos/${{ github.repository }}/pulls?head=${{ github.repository_owner }}:${{ github.ref_name }}")
          if(length(prs)) write("REDUNDANT=yes", Sys.getenv("GITHUB_ENV"), append = TRUE)
        shell: Rscript {0}

      - name: Check out HEAD
        if: env.REDUNDANT != 'yes'
        uses: actions/checkout@v4
        with:
          path: head

      - name: Select BASE
        if: env.REDUNDANT != 'yes'
        run: |
          if [[ ${{ github.event_name }}=="pull_request" ]]
          then # PR -> base branch
            echo "BASEREF=${{ github.event.pull_request.base.ref }}" >> "$GITHUB_ENV"
          elif [[ ${{ github.ref_name }}==${{ github.event.repository.default_branch }} ]]
          then # default branch -> previous push
            echo "BASEREF=${{ github.event.before }}" >> "$GITHUB_ENV"
          else # otherwise -> default branch
            echo "BASEREF=${{ github.event.repository.default_branch }}" >> "$GITHUB_ENV"
          fi

      - name: Check out BASE
        uses: actions/checkout@v4
        if: env.REDUNDANT != 'yes'
        with:
          path: base
          ref: ${{ env.BASEREF }}

      - uses: r-lib/actions/setup-r-dependencies@v2
        if: env.REDUNDANT != 'yes'
        with:
          extra-packages: |
            any::gh
            any::lintr
            any::purrr
            any::stringr
          needs: check
          working-directory: base

      - uses: r-lib/actions/setup-r-dependencies@v2
        if: env.REDUNDANT != 'yes'
        with:
          needs: check
          working-directory: head

      - name: Add lintr options
        if: env.REDUNDANT != 'yes'
        run: |
          cat('\noptions(lintr.linter_file = ".lintr")\n', file = "~/.Rprofile", append = TRUE)
        shell: Rscript {0}

      - name: Install package
        if: env.REDUNDANT != 'yes'
        run: R CMD INSTALL head

      - name: Lint both versions and return only the difference.
        if: env.REDUNDANT != 'yes'
        run: |
          source("head/.github/workflows/lintr-diff.R")
          files <- tryCatch(
            gh::gh("GET https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"),
            error = function(e) gh::gh("GET /repos/${{ github.repository }}/compare/${{ env.BASEREF }}...${{ github.ref_name }}")$files)
          writeLines(lintr_filter(files))
        shell: Rscript {0}
        env:
          LINTR_ERROR_ON_LINT: false
